
trigger:
- main

pool:
  vmImage: linux-latest

variables:
  imageName: pipelines-javascript-docker

steps:

- task: Docker@2
  displayName: Build an Image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile